name: 部署到 GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限
permissions:
  contents: read
  pages: write
  id-token: write

# 允许一个并发部署
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      
      - name: 设置 Pages
        uses: actions/configure-pages@v4
      
      - name: 设置 Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      
      - name: 安装依赖
        run: |
          gem install jekyll jekyll-feed jekyll-paginate
      
      - name: 构建网站
        run: jekyll build
        env:
          JEKYLL_ENV: production
      
      - name: 上传构建结果
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_site/"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
